### ISSUE TITLE
react-intl-cra not working with es6 decorators

### ISSUE THREAD

**Issue by gauravmakkar** [MCS-Lite/mcs-lite#480]
**PACKAGES**

*   react-intl-cra

**
> react-intl-cra './src/**/*.js' './messages.json'

{ SyntaxError: unknown: Unexpected token (9:1)
   7 | const defaultStyle = {};
   8 | 
>  9 |  @NotificationBar
     |  ^
  10 | export default class BarcodeInputWrapper extends Component {
  11 | 
**

**Comment by evenchange4** [comment]
The `react-intl-cra` CLI is based on CRA (Create-React-App), and it [doesn’t support decorator syntax at the moment](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#can-i-use-decorators). 

React-intl-cra is just a workaround for [create-react-app #1227](https://github.com/facebookincubator/create-react-app/issues/1227#issuecomment-285738137) and [react-intl #869](https://github.com/yahoo/react-intl/issues/869) in unofficial way. If you already eject the CRA project, I recommend using the [official way](https://github.com/yahoo/babel-plugin-react-intl) to extract the message files. 😄

**Comment by evenchange4** [comment]
Close it. I moved `react-intl-cra` to [standalone repo](https://github.com/evenchange4/react-intl-cra). Please feel free to create issues there if you have any problems.
